// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhlox5gqUVA9bgJfsabp6iOYxvaLG6MqU',
    appId: '1:143734232601:web:9a8392a1661839d3f0bc88',
    messagingSenderId: '143734232601',
    projectId: 'tasky-app-26a30',
    authDomain: 'tasky-app-26a30.firebaseapp.com',
    storageBucket: 'tasky-app-26a30.appspot.com',
    measurementId: 'G-13ZVN08X8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2P-90yios1RU7vl4F764uUcy_66FLBwM',
    appId: '1:143734232601:android:afe9611f595c875af0bc88',
    messagingSenderId: '143734232601',
    projectId: 'tasky-app-26a30',
    storageBucket: 'tasky-app-26a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGo0bVOfUGR_Ur1RSyTRaYhHVpYOYlMCs',
    appId: '1:143734232601:ios:db8394dcc141033ef0bc88',
    messagingSenderId: '143734232601',
    projectId: 'tasky-app-26a30',
    storageBucket: 'tasky-app-26a30.appspot.com',
    androidClientId: '143734232601-9a8fsmo5hkjad76q0m6cbc4bmrhn6cee.apps.googleusercontent.com',
    iosClientId: '143734232601-c65hgbqfdo04k17cjm3oddi1ctj4s1b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskyApp',
  );
}
